server:
  port: 8181
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ExceptionHandling
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


management:
  endpoints:
    web:
      exposure:
        include: "*"

