server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ExceptionHandling
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


